on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

name: Coverage Report

jobs:
  build:
    strategy:
      matrix:
        platform: [ubuntu-latest]
    runs-on: ${{ matrix.platform }}
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: 10.15.1
      - run: |
          npm ci
          npm test
          npm run build

  coverage:
    needs: build
    name: Coverage Report
    runs-on: ubuntu-latest
    env:
      COVERALLS_REPO_TOKEN: "${{ secrets.COVERALLS_REPO_TOKEN }}"
      COVERALLS_GIT_BRANCH: "${{ github.ref }}"
    steps:
      - uses: actions/checkout@v1

      - name: Use Node.js 10.x
        uses: actions/setup-node@v1
        with:
          node-version: 10.15.1

      - name: npm ci, npm run coverage
        run: |
          npm ci
          npm run coverage

      - name: Coveralls
        uses: coverallsapp/github-action@master
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
